[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$uiRoot = Join-Path $repoRoot "web/ui"
$npmCache = Join-Path $repoRoot ".cache/npm"

function Invoke-Checked {
    param(
        [string]$FilePath,
        [string[]]$Arguments,
        [string]$WorkingDirectory
    )

    Push-Location $WorkingDirectory
    try {
        & $FilePath @Arguments
        if ($LASTEXITCODE -ne 0) {
            throw "$FilePath $($Arguments -join ' ') failed in $WorkingDirectory"
        }
    }
    finally {
        Pop-Location
    }
}

function Write-GzipFile {
    param(
        [string]$SourcePath,
        [string]$DestinationPath
    )

    $sourceBytes = [System.IO.File]::ReadAllBytes($SourcePath)
    $destinationStream = [System.IO.File]::Create($DestinationPath)
    try {
        $gzipStream = New-Object System.IO.Compression.GzipStream($destinationStream, [System.IO.Compression.CompressionLevel]::Optimal)
        try {
            $gzipStream.Write($sourceBytes, 0, $sourceBytes.Length)
        }
        finally {
            $gzipStream.Dispose()
        }
    }
    finally {
        $destinationStream.Dispose()
    }
}

Push-Location $repoRoot

try {
    New-Item -ItemType Directory -Force $npmCache | Out-Null
    $env:npm_config_cache = (Resolve-Path $npmCache).Path

    Invoke-Checked -FilePath "npm.cmd" -Arguments @("ci") -WorkingDirectory $uiRoot

    $lezerRoot = Join-Path $uiRoot "module/lezer-promql"
    Invoke-Checked -FilePath "npx.cmd" -Arguments @("lezer-generator", "src/promql.grammar", "-o", "src/parser") -WorkingDirectory $lezerRoot
    [System.IO.File]::AppendAllText((Join-Path $lezerRoot "src/parser.js"), [Environment]::NewLine + [System.IO.File]::ReadAllText((Join-Path $lezerRoot "src/parser.terms.js")))

    $parserTerms = [System.IO.File]::ReadAllText((Join-Path $lezerRoot "src/parser.terms.js"))
    $parserTypes = [System.Text.RegularExpressions.Regex]::Replace($parserTerms, " = [0-9]+", ": number")
    $lezerTypeFile = @(
        "// Copyright 2021 The Prometheus Authors"
        "//"
        "// Licensed under the Apache License, Version 2.0 (the ""License"");"
        "// you may not use this file except in compliance with the License."
        "// You may obtain a copy of the License at"
        "//"
        "//    http://www.apache.org/licenses/LICENSE-2.0"
        "//"
        "// Unless required by applicable law or agreed to in writing, software"
        "// distributed under the License is distributed on an ""AS IS"" BASIS,"
        "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."
        "// See the License for the specific language governing permissions and"
        "// limitations under the License."
        ""
        "// This file was generated by lezer-promql. You probably should not edit it."
        "import { LRParser } from '@lezer/lr'"
        ""
        "export const parser: LRParser"
        $parserTypes.TrimEnd()
        ""
    ) -join [Environment]::NewLine

    New-Item -ItemType Directory -Force (Join-Path $lezerRoot "dist") | Out-Null
    [System.IO.File]::WriteAllText((Join-Path $lezerRoot "dist/index.d.ts"), $lezerTypeFile)
    Invoke-Checked -FilePath "npx.cmd" -Arguments @("rollup", "-c") -WorkingDirectory $lezerRoot
    Copy-Item -LiteralPath (Join-Path $lezerRoot "src/tokens.js") -Destination (Join-Path $lezerRoot "dist/tokens.js") -Force
    Copy-Item -LiteralPath (Join-Path $lezerRoot "src/highlight.js") -Destination (Join-Path $lezerRoot "dist/highlight.js") -Force
    Copy-Item -LiteralPath (Join-Path $lezerRoot "src/parser.terms.js") -Destination (Join-Path $lezerRoot "dist/parser.terms.js") -Force

    $codemirrorRoot = Join-Path $uiRoot "module/codemirror-promql"
    Invoke-Checked -FilePath "npx.cmd" -Arguments @("tsc", "--module", "esnext", "--target", "es2018", "--outDir", "dist/esm") -WorkingDirectory $codemirrorRoot
    Invoke-Checked -FilePath "npx.cmd" -Arguments @("tsc", "--module", "commonjs", "--target", "es5", "--outDir", "dist/cjs", "--downlevelIteration") -WorkingDirectory $codemirrorRoot

    $env:GENERATE_SOURCEMAP = "false"
    $env:DISABLE_ESLINT_PLUGIN = "true"
    Invoke-Checked -FilePath "npm.cmd" -Arguments @("run", "build", "-w", "@prometheus-io/app") -WorkingDirectory $uiRoot

    $reactStaticRoot = Join-Path $uiRoot "static/react"
    if (Test-Path $reactStaticRoot) {
        Remove-Item -LiteralPath $reactStaticRoot -Recurse -Force
    }
    Move-Item -LiteralPath (Join-Path $uiRoot "react-app/build") -Destination $reactStaticRoot

    $embedTemplate = [System.IO.File]::ReadAllText((Join-Path $uiRoot "embed.go.tmpl")).TrimEnd()
    $staticRoot = Join-Path $uiRoot "static"
    Get-ChildItem $staticRoot -Recurse -File -Filter *.gz | Remove-Item -Force

    $embedLines = New-Object System.Collections.Generic.List[string]
    foreach ($file in Get-ChildItem $staticRoot -Recurse -File | Sort-Object FullName) {
        $gzipPath = "$($file.FullName).gz"
        Write-GzipFile -SourcePath $file.FullName -DestinationPath $gzipPath

        $relativePath = $gzipPath.Substring($uiRoot.Length + 1).Replace('\', '/')
        $embedLines.Add("//go:embed $relativePath")
    }
    $embedLines.Add("var EmbedFS embed.FS")
    [System.IO.File]::WriteAllText((Join-Path $uiRoot "embed.go"), $embedTemplate + [Environment]::NewLine + [Environment]::NewLine + ($embedLines -join [Environment]::NewLine) + [Environment]::NewLine)
}
finally {
    Pop-Location
}
